apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyma 
  labels:
    app: kyma 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyma 
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: kyma  
    spec:     # pod spec                  
      containers: 
      - image: ghcr.io/apkunte/kyma:latest # image we pushed
        name: kyma  
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4004
---
apiVersion: v1
kind: Service
metadata:
  name: kyma 
  labels:
    app: kyma
spec:
  ports:
  - name: http
    port: 4004
    targetPort: 4004
  selector:
    app: kyma 
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: kyma
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: kyma
    name: kyma
    port: 4004