apiVersion: v1
kind: Secret
metadata:
  name: kyma-db-secret
type: opaque
stringData:
  VCAP_SERVICES: >
    {
        "hana": [
            {
            "binding_name": null,
            "credentials": {
          "host": "87061339-55d4-4569-8c20-3274ccc0b6a4.hana.trial-us10.hanacloud.ondemand.com",
          "port": "443",
          "driver": "com.sap.db.jdbc.Driver",
          "url": "jdbc:sap://87061339-55d4-4569-8c20-3274ccc0b6a4.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=C9AD68026EBF4CFFAACA6C382F031AA8",
          "schema": "C9AD68026EBF4CFFAACA6C382F031AA8",
          "hdi_user": "C9AD68026EBF4CFFAACA6C382F031AA8_DXIUT4HI727QT6QBL0FETHGZ6_DT",
          "hdi_password": "Xe6Y9uCiRdkMeBikaiKOihSCYeNlTfWCbuRi9jtUpKM9rVOeoTUGqWcwQLCWokF1iDH8mnvqKyqbDNBv0RQ2w-XZsIudBnTuxxx-s_mVxirM54k5wSYIQyUKCbuNCZUF",
          "user": "C9AD68026EBF4CFFAACA6C382F031AA8_DXIUT4HI727QT6QBL0FETHGZ6_RT",
          "password": "Fz01zC5ndsfZA.qof68uJOTnjNQcb1CZWsygj8i4NyzEUftjrr4j-H-JBqyGc4DQ5W0vJ4HW-IqyUbK9FG8BqYZQ_n9zSr2C3U9ucJFA8blZCbBHvF5t3P5tGoq7yGeX",
          "certificate": "-----BEGIN CERTIFICATE-----\nMIIDrzCCApegAwIBAgIQCDvgVpBCRrGhdWrJWZHHSjANBgkqhkiG9w0BAQUFADBh\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBD\nQTAeFw0wNjExMTAwMDAwMDBaFw0zMTExMTAwMDAwMDBaMGExCzAJBgNVBAYTAlVT\nMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5j\nb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IENBMIIBIjANBgkqhkiG\n9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4jvhEXLeqKTTo1eqUKKPC3eQyaKl7hLOllsB\nCSDMAZOnTjC3U/dDxGkAV53ijSLdhwZAAIEJzs4bg7/fzTtxRuLWZscFs3YnFo97\nnh6Vfe63SKMI2tavegw5BmV/Sl0fvBf4q77uKNd0f3p4mVmFaG5cIzJLv07A6Fpt\n43C/dxC//AH2hdmoRBBYMql1GNXRor5H4idq9Joz+EkIYIvUX7Q6hL+hqkpMfT7P\nT19sdl6gSzeRntwi5m3OFBqOasv+zbMUZBfHWymeMr/y7vrTC0LUq7dBMtoM1O/4\ngdW7jVg/tRvoSSiicNoxBN33shbyTApOB6jtSj1etX+jkMOvJwIDAQABo2MwYTAO\nBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUA95QNVbR\nTLtm8KPiGxvDl7I90VUwHwYDVR0jBBgwFoAUA95QNVbRTLtm8KPiGxvDl7I90VUw\nDQYJKoZIhvcNAQEFBQADggEBAMucN6pIExIK+t1EnE9SsPTfrgT1eXkIoyQY/Esr\nhMAtudXH/vTBH1jLuG2cenTnmCmrEbXjcKChzUyImZOMkXDiqw8cvpOp/2PV5Adg\n06O/nVsJ8dWO41P0jmP6P6fbtGbfYmbW0W5BjfIttep3Sp+dWOIrWcBAI+0tKIJF\nPnlUkiaY4IBIqDfv8NZ5YBberOgOzW6sRBc4L0na4UU+Krk2U886UAb3LujEV0ls\nYSEY1QSteDwsOoBrp+uvFRTp2InBuThs4pFsiv9kuXclVzDAGySj4dzp30d8tbQk\nCAUw7C29C79Fv1C5qfPrmAESrciIxpg0X40KPMbp1ZWVbd4=\n-----END CERTIFICATE-----"
        }
            "instance_name": "hana",
            "label": "hana",
            "name": "hana",
            "plan": "hdi-shared",
            "provider": null,
            "syslog_drain_url": null,
            "tags": [
              "hana",
              "database",
              "relational"
            ],
            "volume_mounts": []
            }
        ]
    }