name: Build and publish Docker image

on:
  push:
    branches: [ master ]
env:
  HUB: https://ghcr.io
  TAG: latest
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build image ${{ github.event.inputs.app }} for ${{ github.event.inputs.componentdir }} from ${{ github.event.inputs.dir }}
      run: |
          docker build -f ./Dockerfile \
          -t ${HUB}/${GITHUB_REPOSITORY}/${{ github.event.inputs.app }}:${TAG} \
          ${{ github.event.inputs.dir }}
      
    - name: Push the image to GitHub Package Registry
      if: ${{ success() }}
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ${HUB} --username ${USER} --password-stdin
        docker push ${HUB}/${GITHUB_REPOSITORY}/Kyma:${TAG}
